In [ ]:
#numpypractice

In [ ]:
#Creating Single dimensional array

In [ ]:
import numpy as np

n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [ ]:
#Creating Multi-Dimensional Array

In [ ]:
import numpy as np

n2=np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [ ]:
type(n2)

numpy.ndarray

In [ ]:
#Extracting elements

In [ ]:
n1

array([10, 20, 30, 40])

In [ ]:
n1[0]

10

In [ ]:
n1[1:3]

array([20, 30])

In [ ]:
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [ ]:
n2[0,0]

10

In [ ]:
n2[0]

array([10, 20, 30, 40])

In [ ]:
n2[1,3]

10

In [ ]:
#np.zeros

In [ ]:
import numpy as np
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [ ]:
import numpy as np
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#np.arange

In [ ]:
import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
import numpy as np
n1=np.arange(10,50,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
#np.full

In [ ]:
import numpy as np
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [ ]:
#np.randit

In [ ]:
import numpy as np
n1=np.random.randint(1,100,5)
n1

array([ 9, 37, 53, 54,  1])

In [ ]:
n1.shape

(5,)

In [ ]:
import numpy as np
n1=np.array([[1,2,3],[4,5,6]])
n1.shape

(2, 3)

In [ ]:
#NumPy Shape

In [ ]:
n1.shape = (3,2)
n1.shape

(3, 2)

In [ ]:
#Numpy Sum

In [ ]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])

np.sum([n1,n2])

100

In [ ]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [ ]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [ ]:
#NumPy comparison

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([10,30,20])

np.equal(n1,n2)

array([ True, False, False])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([10,30,20])

np.array_equal(n1,n2)

False

In [ ]:
#Joining Arrays

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n1=n1/2
n1

array([ 5., 10., 15.])

In [ ]:
n1=n1+1
n1

array([ 6., 11., 16.])

In [ ]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])

In [ ]:
np.intersect1d(n1,n2)

array([50, 60])

In [ ]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [ ]:
#numpy math functions

In [ ]:
import numpy as np
n1=np.array([1,5,3,100,4,48])
np.std(n1)

36.59424666377065